### ISSUE TITLE
Writing R code in a DCF is unappealing

### ISSUE THREAD

**Issue by hadley** [r-lib/lintr#1210]
Since you don't get syntax highlighting, help, autocomplete, ...

What do you think about supporting some additional way of defining custom linters that uses a file with a `.R` extension?

**Comment by AshesITR** [comment]
Rather minimal changes to the `.lintr` file would make it parseable R code, though. I'd be okay with allowing `.lintr` to also (in addition to being dcf-formatted) be parseable R code, restricted to assigning the lintr config variables, i.e., for our `.lintr`

```r
linters <- linters_with_defaults( # The following TODOs are part of an effort to have {lintr} lint-free (#584)
   line_length_linter = line_length_linter(120),
   # TODO add implicit_integer_linter()
   cyclocomp_linter = cyclocomp_linter(37), # TODO reduce to 15
)
exclusions <- list(
  "inst/doc/creating_linters.R" = 1,
  "inst/example/bad.R",
  "tests/testthat/default_linter_testcode.R",
  "tests/testthat/dummy_packages",
  "tests/testthat/dummy_projects",
  "tests/testthat/exclusions-test",
  "tests/testthat/knitr_formats",
  "tests/testthat/knitr_malformed"
)
```

@MichaelChirico WDYT?

**Comment by hadley** [comment]
Allowing `.lintr` to be either DCF or R doesn't seem that appealing to me either. I was thinking more of something like `_lintr.R`

There's some related art in Roxygen2 — you can configure simple options in `DESCRIPTION` or provide `man/roxygen/meta.R` if you want to run R code.

**Comment by AshesITR** [comment]
Not a big fan of allowing two separate configuration files - what to do if both files exist in the same directory?
`pkgdown`, `blogdown`, `covr` and GitHub Actions use YAML for configuration, by the way. I've never heard of the `man/roxygen/meta.R` feature.

I must admit though, that the DCF format took a bit to get used to, especially the akward indentation requirements.

**Comment by AshesITR** [comment]
Hmm that seems hard because we intend on `linters` being configured via `linters_with_defaults()` or `linters_with_tags()`.
For a transitional period, I'd be fine if `.lintr` would be parsed as YAML and, if that fails, as DCF with a deprecation warning.
I guess the question is, can we avoid R code by leveraging the YAML structure, e.g. using

```yaml
linters:
  - with: defaults
    line_length_linter:
      length: 120
    cyclocomp_linter:
      limit: 37
exclusions:
 - inst/doc/creating_linters.R: 1
 - inst/example/bad.R
 - tests/testthat/default_linter_testcode.R
 - tests/testthat/dummy_packages
 - tests/testthat/dummy_projects
 - tests/testthat/exclusions-test
 - tests/testthat/knitr_formats
 - tests/testthat/knitr_malformed
```
