### ISSUE TITLE
Build release and development versions of package website

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#1456]
We need to start having separate versions of the website for the release and development package versions, so that the users are not confused by why the output they see doesn't match with what's on the website. 

We can only do this after the next release of the package. If we do it now, IINM, the release website will disappear.

We just need to add the following to `_pkgdown.yml`.

```yml
development:
  mode: auto
  version_label: default      # optional
  version_tooltip: "Version"  # optional
```

For more, see:
https://pkgdown.r-lib.org/articles/how-to-update-released-site.html
